### ISSUE TITLE
Screens 1-4 and Crossover between them

### ISSUE THREAD

**Issue by orpgol** [shenkarlab/pensyaTeam#6]
Good Luck tamar

**Comment by Tamary** [comment]
@mushon, We have two questions -
1. Can we use the Pensya companies' logos? We want to use in the screen where the user has to say which Pensya company he's using.
2. We were thinking about having the pensya bag at the left appear only after the stage where he goes to work, because until then nothing really happens with it... What do you think? 

Thanks :)
